#!/bin/bash

# Source configuration file
source /usr/local/bin/upcaddy_files/config.cfg

# Show the menu (includes head using cat)
cat /usr/local/bin/upcaddy_files/head

echo ""
echo "Please select an option:"
echo "1. Create a new .caddy file"
echo "2. Consolidate .caddy files and update Caddy"
echo "3. Exit"
echo ""

# Read user selection
read -p "Enter your choice (1-3): " choice

# Handle selection
case $choice in
  1)
    echo "Please select the new config type:"
    echo "1. Standard subdomain on ${DOMAIN}"
    echo "   Select this if your subdomain on ${DOMAIN}'s A record points to this systems' public IP address"
    echo "2. Forward subdomain on ${DOMAIN} to another site"
    echo "   Select if you're exposing a service from another system via port 80/443"
    echo "3. Subdomain on private subdomain (${PRIVATE_SUBDOMAIN}.${DOMAIN})"
    echo "   Select if you're proxying your serivce to sub.${PRIVATE_SUBDOMAIN}.${DOMAIN} from a service running on a private IP address "
    echo "4. Subdomain on (${PRIVATE_SUBDOMAIN}.${DOMAIN})"
    echo "   Select if you're proxying your serivce to another Caddy server via port 80/443 "
    read -p "Enter your choice (1-3): " sub_choice
    case $sub_choice in
      1) /usr/local/bin/upcaddy_files/new1_subdomain ;;
      2) /usr/local/bin/upcaddy_files/new2_subdomain_forward ;;
      3) /usr/local/bin/upcaddy_files/new3_sub-subdomain ;;
      4) /usr/local/bin/upcaddy_files/new4_subdomain_combined ;;
      *) echo "Invalid option. Exiting."; exec /usr/local/bin/upcaddy ;;
    esac
    ;;
  2)
    echo "Consolidate Caddyfile and restart Caddy"
    /usr/local/bin/upcaddy_files/update
    ;;
  3)
    echo "Exiting..."
    exit 0
    ;;
  *)
    echo "Invalid option. Exiting."
    exit 1
    ;;
esac
